---
kind: Template
apiVersion: v1
metadata:
  name: dynatrace-credentials-template
  annotations:
    description: Credentials template for dynatrace oneagent operator deployment
objects:
- kind: "OneAgent"
  apiVersion: "dynatrace.com/v1alpha1"
  metadata:
    name: "oneagent-operator"
    namespace: "${NAMESPACE}"
    labels:
      dynatrace: operator
      operator: oneagent
  spec:
    apiUrl: "${API_URL}"
    apiToken: "${API_TOKEN}"
    paasToken: "${PAAS_TOKEN}"
parameters:
- name: API_URL
  displayName: API URL for Dynatrace Tenant
  description: API URL for Dynatrace Tenant
  required: true
- name: API_TOKEN
  displayName: API Token
  description: API Token for Dynatrace OneAgent
  required: true
- name: PAAS_TOKEN
  displayName: PaaS Token
  description: PaaS Token for Dynatrace OneAgent
  required: true
- name: NAMESPACE
  displayName: Deployment Namespace
  description: Namespace (or project) used for deployment
  required: true
  value: dynatrace
